services:
  master_postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'

#  sonarqube:
#    image: sonarqube:community
#    ports:
#      - "9000:9000"
#    environment:
#      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
#      - SONAR_JDBC_URL=jdbc:postgresql://master_postgres:5432/postgres
#      - SONAR_JDBC_USERNAME=user
#      - SONAR_JDBC_PASSWORD=password
#      - SONAR_WEB_JDBC_USERNAME=user
#      - SONAR_WEB_JDBC_PASSWORD=password
#      - SONAR_AUTH_ADMIN_LOGIN=admin
#      - SONAR_AUTH_ADMIN_PASSWORD=admin
#    volumes:
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#
#volumes:
#  sonarqube_data:
#  sonarqube_extensions: