spring:
  application:
    name: entrance-examination
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: KEBAB_CASE
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  # does not make db queries after leaving service level
#  jpa:
#    open-in-view: false

  # no autoconfiguration for spring security
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  # reduced logging
#logging:
#  level:
#    root: WARN
#    com.nksoft: INFO

server:
  servlet:
    context-path: /api/v1
  address: 0.0.0.0
  port: 8080

springdoc:
  swagger-ui:
    path: /docs