spring:
  profiles:
    active: dev
  application:
    name: entrance-examination
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: KEBAB_CASE
    default-property-inclusion: non_null

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 125MB

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
        order_updates: true
#        generate_statistics: true


  # TODO: Change later for lazy init
#  jpa:
#    open-in-view: false

  # no autoconfiguration for spring security
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

custom:
  student:
    choices:
      min: 3
      max: 10
      choice-submission-deadline: 2025-07-25T15:00:00
  normalization:
    rescaled-mean: 50
    rescaled-sd: 10

server:
  servlet:
    context-path: /api/v1
  address: 0.0.0.0
  port: 8080

springdoc:
  swagger-ui:
    path: /docs