spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: DEBUG
    com.nksoft: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.hibernate.SQL: DEBUG