spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: INFO
    com.nksoft: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: OFF
    org.hibernate.SQL: WARN
  file:
    name: logs/app.log